# -*- coding: utf-8 -*-
"""Assignment 7 Linked List

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oq4oQvoL-Vet3K1r6NyygTPywNXhaLiA

##LAPORAN PRAKTIKUM: LINKED LIST

##Judul Praktikum

"Implementasi Strtukr Data Linked List"

##Tujuan Praktikum

1. Memahami konsep dasar Linked List sebagai struktur data dinamis.
2. Memahami struktur node yang terdiri dari data dan pointer.
3. Mengimplementasikan Single Linked List menggunakan Python.
4. Mengimplementasikan operasi dasar Linked List seperti insert, delete, search, dan traversal.
5. Memahami konsep Doubly Linked List dan Circular Linked List.
6. Menganalisis kelebihan, kekurangan, dan kompleksitas operasi pada Linked List.

##Dasar Teori

Linked List adalah struktur data linear yang terdiri dari sekumpulan node yang saling terhubung melalui pointer atau referensi. Setiap node memiliki dua bagian utama, yaitu data untuk menyimpan nilai dan pointer (next) yang digunakan untuk menunjuk ke node berikutnya. Berbeda dengan array yang menyimpan data secara berurutan di memori, Linked List menyimpan data secara dinamis sehingga lebih fleksibel dalam proses penambahan dan penghapusan data.

Terdapat beberapa jenis Linked List, yaitu Singly Linked List, Doubly Linked List, dan Circular Linked List. Singly Linked List hanya memiliki satu pointer ke node berikutnya, Doubly Linked List memiliki pointer ke node sebelumnya dan berikutnya, sedangkan Circular Linked List menghubungkan node terakhir kembali ke node pertama sehingga membentuk lingkaran.

Operasi dasar pada Linked List meliputi traversal untuk menampilkan seluruh data, insertion untuk menambahkan node baru, deletion untuk menghapus node, dan searching untuk mencari data tertentu. Struktur data ini banyak digunakan dalam berbagai aplikasi seperti playlist musik, browser history, sistem reservasi, editor teks, manajemen memori, serta sebagai dasar implementasi struktur data lain seperti Stack dan Queue.

##Tugas 1 - Membuat Node Sederhana dan Menampilkan Datanya
"""

class Node:
    def __init__(self, data):
        self.data = data

node1 = Node(10)

print("Data Node:", node1.data)

"""> Langkah Pengerjaan

1. Membuat class Node.
2. Menambahkan atribut data.
3. Membuat objek node dengan nilai 10.
4. Menampilkan isi node.

> Analisis

Node merupakan komponen dasar pada Linked List yang digunakan untuk menyimpan data. Pada program ini node hanya berisi satu data yaitu 10.

> Kesimpulan

Node dapat digunakan untuk menyimpan data sebelum dihubungkan dengan node lain dalam Linked List.

##Tugas 2 - Membuat Lnkked List Berisi 5 Angka
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

node1 = Node(10)
node2 = Node(20)
node3 = Node(30)
node4 = Node(40)
node5 = Node(50)

node1.next = node2
node2.next = node3
node3.next = node4
node4.next = node5

print("Linked List berhasil dibuat")

"""> Langka Kerja

1. Membuat 5 node.
2. Menghubungkan setiap node menggunakan next.
3. Membentuk Linked List dari 10 sampai 50.

> Analisis

Setiap node terhubung ke node berikutnya sehingga membentuk rangkaian data yang saling terkait.

> Kesimpulan

Linked List dapat dibentuk dengan menghubungkan beberapa node menggunakan pointer next.

##Tugas 3 - Traversal Seluruh Node
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

node1 = Node(10)
node2 = Node(20)
node3 = Node(30)
node4 = Node(40)
node5 = Node(50)

node1.next = node2
node2.next = node3
node3.next = node4
node4.next = node5

current = node1

while current:
    print(current.data)
    current = current.next

"""> Langkah Kerja

1. Membuat Linked List.
2. Menentukan node pertama sebagai awal traversal.
3. Menampilkan data satu per satu hingga node terakhir.

> Analisis

Traversal dilakukan dengan mengikuti hubungan antar node dari awal sampai akhir.

> Kesimpulan

Traversal digunakan untuk membaca seluruh data yang terdapat dalam Linked List.

##Tugas 4 - Menambahkan Node di Awal Linked List
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

head = Node(20)
head.next = Node(30)

node_baru = Node(10)
node_baru.next = head
head = node_baru

current = head
while current:
    print(current.data)
    current = current.next

"""> Langkah Kerja

1. Membuat Linked List awal.
2. Membuat node baru dengan nilai 10.
3. Menghubungkan node baru ke head lama.
4. Menjadikan node baru sebagai head.

> Analisis

Penambahan node di awal cukup mengubah referensi head tanpa menggeser data lain.

> Kesimpulan

Insert di awal Linked List lebih efisien dibandingkan Array.

##Tugas 5 - Menambahkan Node di Akhir Linked List
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

head = Node(10)
head.next = Node(20)

node_baru = Node(30)

current = head
while current.next:
    current = current.next

current.next = node_baru

current = head
while current:
    print(current.data)
    current = current.next

"""> Langkah Kerja

1. Membuat Linked List.
2. Menelusuri hingga node terakhir.
3. Menambahkan node baru di akhir.

> Analisis

Program harus mencari node terakhir terlebih dahulu sebelum melakukan penambahan.

> Kesimpulan

Penambahan node di akhir Linked List memerlukan proses traversal terlebih dahulu.

##Tugas 6 - Menghapus Node Tertentu
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

head = Node(10)
node2 = Node(20)
node3 = Node(30)

head.next = node2
node2.next = node3

head.next = node3

current = head
while current:
    print(current.data)
    current = current.next

"""> Langkah Kerja

1. Membuat Linked List.
2. Menentukan node yang akan dihapus.
3. Mengubah hubungan antar node.
4. Menampilkan hasil.

> Analisis

Node bernilai 20 dihapus dengan menghubungkan node 10 langsung ke node 30.

> Kesimpulan

Penghapusan node dilakukan dengan mengubah referensi antar node.

##Tugas 7 - Mencari Data pada Linked List
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

head = Node(10)
head.next = Node(20)
head.next.next = Node(30)

cari = 20
current = head

while current:
    if current.data == cari:
        print("Data ditemukan")
        break
    current = current.next
else:
    print("Data tidak ditemukan")

"""> Langkah Kerja

1. Membuat Linked List.
2. Menentukan data yang dicari.
3. Melakukan pencarian dari node pertama hingga terakhir.

> Analisis

Setiap node diperiksa satu per satu sampai data ditemukan.

> Kesimpulan

Proses pencarian pada Linked List dilakukan secara berurutan.

##Tugas 8 - Menghitung Jumlah Node
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

head = Node(10)
head.next = Node(20)
head.next.next = Node(30)

jumlah = 0
current = head

while current:
    jumlah += 1
    current = current.next

print("Jumlah node:", jumlah)

"""> Langkah Kerja

1. Membuat Linked List.
2. Menelusuri seluruh node.
3. Menghitung jumlah node yang ada.

> Analisis

Variabel penghitung bertambah setiap kali menemukan node baru.

> Kesimpulan

Jumlah node diperoleh dengan melakukan traversal pada seluruh Linked List.

##Tugas 9 - Implementasi Doubly Linked List
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.prev = None
        self.next = None

node1 = Node("A")
node2 = Node("B")
node3 = Node("C")

node1.next = node2
node2.prev = node1

node2.next = node3
node3.prev = node2

print(node1.data, node2.data, node3.data)

"""> Langkah Kerja

1. Membuat node dengan pointer prev dan next.
2. Menghubungkan node ke depan dan belakang.
3. Menampilkan data.

> Analisis

Setiap node dapat diakses dari dua arah sehingga lebih fleksibel.

> Kesimpulan

Doubly Linked List memungkinkan navigasi maju dan mundur.

##Tugas 10 - Implementasi Circular Linked List
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

node1 = Node("A")
node2 = Node("B")
node3 = Node("C")

node1.next = node2
node2.next = node3
node3.next = node1

print("Circular Linked List berhasil dibuat")

"""> Langkah Kerja

1. Membuat beberapa node.
2. Menghubungkan node terakhir ke node pertama.
3. Membentuk struktur melingkar.

> Analisis

Tidak terdapat node yang menunjuk ke None karena node terakhir kembali ke node pertama.

> Kesimpulan

Circular Linked List cocok digunakan untuk sistem yang berulang secara terus-menerus.

##Tugas 11 - Sistem Playlist Musik menggunakan Linked List
"""

class Lagu:
    def __init__(self, judul):
        self.judul = judul
        self.next = None

lagu1 = Lagu("Mrs. Magic")
lagu2 = Lagu("Golden Brown")
lagu3 = Lagu("Luminary")

lagu1.next = lagu2
lagu2.next = lagu3

current = lagu1

while current:
    print(current.judul)
    current = current.next

"""> Langkah Kerja

1. Membuat node lagu.
2. Menghubungkan setiap lagu.
3. Menampilkan playlist.

> Analisis

Setiap lagu terhubung ke lagu berikutnya sehingga membentuk daftar putar sederhana.

> Kesimpulan

Linked List dapat digunakan untuk mengelola playlist musik secara dinamis.

##Tugas 12 - Browser History menggunakan Doubly Linked List
"""

class Halaman:
    def __init__(self, url):
        self.url = url
        self.prev = None
        self.next = None

google = Halaman("google.com")
youtube = Halaman("youtube.com")
github = Halaman("github.com")

google.next = youtube
youtube.prev = google

youtube.next = github
github.prev = youtube

print("Halaman saat ini:", youtube.url)
print("Back:", youtube.prev.url)
print("Forward:", youtube.next.url)

"""> Langkah Kerja

1. Membuat beberapa halaman web.
2. Menghubungkan halaman menggunakan prev dan next.
3. Menampilkan fitur back dan forward.

> Analisis

Doubly Linked List memungkinkan perpindahan halaman ke depan maupun ke belakang dengan mudah.

> Kesimpulan

Browser history sangat cocok diimplementasikan menggunakan Doubly Linked List karena mendukung navigasi dua arah.

##Tugas 13 - Analisis Kompleksitas

| Operasi       | Kompleksitas |
| ------------- | ------------ |
| Traversal     | O(n)         |
| Search        | O(n)         |
| Insert Awal   | O(1)         |
| Insert Akhir  | O(n)         |
| Delete Awal   | O(1)         |
| Delete Tengah | O(n)         |

> Analisis

Pada Tugas 9–12, sebagian besar proses memerlukan traversal untuk menemukan node tertentu sehingga kompleksitasnya O(n). Operasi yang dilakukan langsung pada head memiliki kompleksitas O(1).

> Kesimpulan

Linked List unggul pada proses penambahan dan penghapusan data, tetapi akses data dan pencarian lebih lambat dibandingkan Array karena harus menelusuri node satu per satu.
"""