# -*- coding: utf-8 -*-
"""Assignment 5 Stack

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157-HrEUU9RFZoGXsWOcNDMcIyRlpd-3b

##LAPORAN PRAKTIKUM - STACK

Nama     : Ariela Safmi Ramdhani

NRP      : 2C2230005

Prodi    : Sains Data

##Judul Praktikum

"Implementasi dan Penerapan Stack (LIFO)"

##Tujuan Praktikum

1. Memahami konsep dasar struktur data Stack.
2. Memahami prinsip kerja LIFO (Last In First Out).
3. Mengimplementasikan operasi dasar Stack seperti Push, Pop, dan Peek menggunakan Python.
4. Menganalisis cara kerja Stack dalam penyelesaian masalah komputasi.
5. Menerapkan Stack pada berbagai studi kasus seperti Browser History dan validasi tanda kurung.
6. Mengembangkan program sederhana berbasis Stack menggunakan Python.

##Dasar Teori

Stack adalah struktur data linear yang bekerja menggunakan prinsip LIFO (Last In First Out), yaitu data yang terakhir masuk akan menjadi data pertama yang keluar. Operasi utama pada Stack meliputi Push (menambah data), Pop (menghapus data teratas), Peek (melihat data teratas), IsEmpty (mengecek apakah Stack kosong), dan Size (menghitung jumlah elemen). Dalam Python, Stack dapat diimplementasikan menggunakan list dengan fungsi append() dan pop(). Struktur data ini banyak digunakan pada fitur Undo-Redo, Browser History, Call Stack, dan validasi tanda kurung.

##Tugas 1 - Program Stack Sederhana
"""

stack = []

stack.append(10)
stack.append(20)
stack.append(30)

print("Isi Stack:", stack)

"""> Langkah Kerja

1. Membuat list kosong sebagai Stack.
2. Menambahkan data menggunakan append().
3. Menampilkan isi Stack.

> Analisis

Program menggunakan list Python sebagai Stack. Data dimasukkan berurutan 10, 20, dan 30. Elemen terakhir (30) berada di posisi paling atas Stack.

> Kesimpulan

Stack dapat dibuat menggunakan list Python dan menerapkan konsep LIFO (Last In First Out).

##Tugas 2 - Operasi Push dan Pop
"""

stack = []

stack.append(10)
stack.append(20)
stack.append(30)

print("Stack Awal:", stack)

data = stack.pop()

print("Data Keluar:", data)
print("Stack Sekarang:", stack)

"""> Langkah Kerja

1. Membuat Stack.
2. Menambahkan data dengan Push (append()).
3. Menghapus data teratas dengan Pop (pop()).
4. Menampilkan hasil.

> Analisis

Saat pop() dijalankan, elemen terakhir yaitu 30 keluar terlebih dahulu. Hal ini menunjukkan prinsip LIFO.

> Kesimpulan

Operasi Push menambah data ke Stack, sedangkan Pop menghapus data paling atas.

##Tugas 3 - Peek
"""

stack = [10, 20, 30]

print("Elemen Teratas:", stack[-1])

"""> Langkah Kerja

1. Membuat Stack.
2. Mengakses elemen terakhir menggunakan indeks -1.
3. Menampilkan elemen teratas.

> Analisis

Peek digunakan untuk melihat data paling atas tanpa menghapusnya dari Stack.

> Kesimpulan

Operasi Peek memungkinkan pengguna mengetahui elemen teratas tanpa mengubah isi Stack.

##Tugas 4 - Menu Stack Interaktif
"""

stack = []

while True:
    print("\n=== MENU STACK ===")
    print("1. Push")
    print("2. Pop")
    print("3. Peek")
    print("4. Tampilkan Stack")
    print("5. Keluar")

    pilihan = input("Pilih menu: ")

    if pilihan == "1":
        data = input("Masukkan data: ")
        stack.append(data)

    elif pilihan == "2":
        if stack:
            print("Data keluar:", stack.pop())
        else:
            print("Stack kosong")

    elif pilihan == "3":
        if stack:
            print("Elemen teratas:", stack[-1])
        else:
            print("Stack kosong")

    elif pilihan == "4":
        print("Isi Stack:", stack)

    elif pilihan == "5":
        break

    else:
        print("Pilihan tidak valid")

"""> Langkah Kerja

1. Membuat menu menggunakan perulangan.
2. Menambahkan fitur Push, Pop, Peek, dan Display.
3. Program berhenti saat memilih menu keluar.

> Analisis

Program memungkinkan pengguna mengelola Stack secara dinamis melalui menu interaktif.

> Kesimpulan

Menu interaktif mempermudah pengoperasian Stack secara langsung.

##Tugas 5 - Menghitung Jumlah Elemen Stack
"""

stack = [10, 20, 30, 40]

print("Jumlah Elemen:", len(stack))

"""> Langkah Kerja

1. Membuat Stack.
2. Menggunakan fungsi len().
3. Menampilkan jumlah elemen.

> Analisis

Fungsi len() menghitung banyaknya data yang tersimpan dalam Stack.

> Kesimpulan

Jumlah elemen Stack dapat diketahui dengan fungsi len().

##Tugas 6 - Simulasi Tumpukan Piring
"""

piring = []

piring.append("Piring 1")
piring.append("Piring 2")
piring.append("Piring 3")

print("Tumpukan:", piring)

ambil = piring.pop()

print("Piring diambil:", ambil)
print("Sisa tumpukan:", piring)

"""> Langkah Kerja

1. Membuat Stack bernama piring.
2. Menambahkan beberapa piring.
3. Mengambil piring paling atas.
4. Menampilkan hasil.

> Analisis

Piring terakhir yang diletakkan akan menjadi piring pertama yang diambil sesuai konsep LIFO.

> Kesimpulan

Stack cocok digunakan untuk simulasi tumpukan benda seperti piring.

##Tugas 7 - Validasi Tanda Kurung
"""

def cek_kurung(ekspresi):
    stack = []

    for karakter in ekspresi:
        if karakter == "(":
            stack.append(karakter)

        elif karakter == ")":
            if not stack:
                return "Tidak Valid"
            stack.pop()

    if not stack:
        return "Valid"
    else:
        return "Tidak Valid"

data = input("Masukkan ekspresi: ")
print(cek_kurung(data))

"""> Langkah Kerja

1. Membaca ekspresi.
2. Menyimpan tanda kurung buka ke Stack.
3. Menghapusnya saat menemukan kurung tutup.
4. Mengecek apakah Stack kosong.

> Analisis

Jika semua pasangan kurung cocok maka Stack kosong di akhir proses sehingga ekspresi valid.

> Kesimpulan

Stack sangat efektif digunakan untuk pengecekan pasangan tanda kurung.

##Tugas 8 - Simulasi Browser History
"""

history = []

while True:
    print("\n1. Kunjungi Halaman")
    print("2. Back")
    print("3. Lihat History")
    print("4. Keluar")

    pilih = input("Pilih: ")

    if pilih == "1":
        halaman = input("Nama halaman: ")
        history.append(halaman)

    elif pilih == "2":
        if history:
            print("Kembali dari:", history.pop())
        else:
            print("History kosong")

    elif pilih == "3":
        print("Riwayat:", history)

    elif pilih == "4":
        break

"""> Langkah Kerja

1. Membuat Stack history.
2. Menambahkan halaman yang dikunjungi.
3. Menggunakan Pop saat tombol Back ditekan.
4. Menampilkan riwayat.

> Analisis

Halaman terakhir yang dikunjungi akan menjadi halaman pertama yang ditinggalkan saat Back ditekan.

> Kesimpulan

Fitur Browser History merupakan penerapan langsung konsep Stack.

##Tugas 9 - Sistem Undo-Redo Sederhana
"""

undo_stack = []
redo_stack = []

while True:
    print("\n1. Tulis")
    print("2. Undo")
    print("3. Redo")
    print("4. Keluar")

    pilih = input("Pilih: ")

    if pilih == "1":
        teks = input("Masukkan teks: ")
        undo_stack.append(teks)
        redo_stack.clear()

    elif pilih == "2":
        if undo_stack:
            data = undo_stack.pop()
            redo_stack.append(data)
            print("Undo:", data)
        else:
            print("Tidak ada data")

    elif pilih == "3":
        if redo_stack:
            data = redo_stack.pop()
            undo_stack.append(data)
            print("Redo:", data)
        else:
            print("Tidak ada data")

    elif pilih == "4":
        break

"""> Langkah Kerja

1. Membuat Stack Undo dan Redo.
2. Menyimpan perubahan pada Undo Stack.
3. Memindahkan data ke Redo Stack saat Undo.
4. Mengembalikan data saat Redo.

> Analisis

Program menggunakan dua Stack agar proses Undo dan Redo berjalan dengan benar.

> Kesimpulan

Sistem Undo-Redo dapat diimplementasikan menggunakan dua buah Stack.

##Tugas 10 - Analisis Kompleksitas

| Operasi | Kompleksitas |
| ------- | ------------ |
| Push    | O(1)         |
| Pop     | O(1)         |
| Peek    | O(1)         |
| IsEmpty | O(1)         |
| Size    | O(1)         |

> Analisis Browser History

- Kunjungi Halaman → Push → O(1)
- Back → Pop → O(1)
- Lihat Halaman Terakhir → Peek → O(1)

> Analisis Undo-Redo

- Menyimpan Perubahan → Push → O(1)
- Undo → Pop + Push → O(1)
- Redo → Pop + Push → O(1)

> Kesimpulan

Seluruh operasi dasar Stack memiliki kompleksitas O(1) karena hanya mengakses elemen pada bagian atas Stack sehingga prosesnya sangat cepat dan efisien.
"""