# -*- coding: utf-8 -*-
"""Assignment 6 Queue & Deque

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_wimEMNvT38p1pyuQ6gJRlmCIAOc4zLv

##LAPORAN PRAKTIKUM: QUEUE DAN DEQUE (DOUBLE ENDED QUEUE)

Nama     : Ariela Safmi Ramdhani

NRP      : 2C2230005

Prodi    : Sains Data

##Judul Praktikum

"Implementasi Queue dan Deque (Double Ended Queue)"

##Tujuan Praktikum

1. Memahami konsep dasar Queue dan Deque sebagai struktur data linear.
2. Memahami prinsip kerja FIFO (First In First Out) pada Queue.
3. Mengimplementasikan operasi dasar Queue seperti Enqueue, Dequeue, Front, dan Rear menggunakan Python.
4. Mengimplementasikan Deque menggunakan modul collections.deque pada Python.
5. Menganalisis efisiensi operasi Queue dan Deque berdasarkan kompleksitas waktunya.
6. Menerapkan Queue dan Deque dalam berbagai kasus nyata seperti antrian bank, rumah sakit, printer queue, dan playlist musik.

##Dasar Teori

Queue adalah struktur data linear yang bekerja berdasarkan prinsip FIFO (First In First Out), yaitu data yang pertama masuk akan menjadi data pertama yang keluar. Queue memiliki dua bagian utama, yaitu Front sebagai posisi elemen pertama dan Rear sebagai posisi elemen terakhir. Operasi dasar pada Queue meliputi Enqueue untuk menambahkan data ke belakang antrian dan Dequeue untuk menghapus data dari depan antrian.

Selain Queue, terdapat Deque (Double Ended Queue) yang merupakan pengembangan dari Queue. Deque memungkinkan penambahan dan penghapusan data dilakukan dari kedua sisi, baik di bagian depan maupun belakang. Dalam Python, Deque dapat diimplementasikan menggunakan modul collections.deque yang lebih efisien dibandingkan list untuk operasi antrian.

Queue dan Deque banyak digunakan dalam kehidupan sehari-hari maupun sistem komputer, seperti antrian nasabah di bank, antrian pasien di rumah sakit, printer queue, process scheduling pada sistem operasi, call center, serta pengelolaan playlist musik. Penggunaan Queue dan Deque membantu proses pengolahan data menjadi lebih teratur, efisien, dan sesuai urutan yang diinginkan.

##Tugas 1 - Membuat Queue Sederhana menggunakan List
"""

queue = []

queue.append("Kit")
queue.append("Anthony")
queue.append("Lili")

print("Isi Queue:", queue)

"""> Langkah Kerja

1. Membuat Queue kosong menggunakan list.
2. Menambahkan data dengan append().
3. Menampilkan isi Queue.

> Analisis

Data masuk secara berurutan yaitu Kit, Anthony, dan Lili. Data pertama yang masuk adalah Andi sehingga akan menjadi data pertama yang keluar.

> Kesimpulan

Queue bekerja dengan prinsip FIFO (First In First Out), yaitu data yang masuk pertama akan keluar pertama.

##Tugas 2 - Operasi Enqueue dan Deque
"""

queue = []

queue.append("Kit")
queue.append("Dorothy")
queue.append("Lili")

print("Queue Awal:", queue)

layani = queue.pop(0)

print("Dilayani:", layani)
print("Queue Sekarang:", queue)

"""> Langkah Kerja

1. Membuat Queue.
2. Menambahkan data menggunakan Enqueue (append()).
3. Menghapus data pertama menggunakan Dequeue (pop(0)).
4. Menampilkan hasil.

> Analisis

Saat Dequeue dilakukan, elemen pertama yaitu Kit keluar lebih dulu karena Queue menggunakan FIFO.

> Kesimpulan

Enqueue digunakan untuk menambah data di belakang antrian, sedangkan Dequeue digunakan untuk menghapus data di depan antrian.

##Tugas 3 - Menampilkan Front dan Rear
"""

queue = ["Kit", "Joffrey", "Lili"]

print("Front :", queue[0])
print("Rear  :", queue[-1])

"""> Langkah Kerja

1. Membuat Queue.
2. Mengakses elemen pertama sebagai Front.
3. Mengakses elemen terakhir sebagai Rear.
4. Menampilkan hasil.

> Analisis

Front menunjukkan data yang akan dilayani terlebih dahulu, sedangkan Rear menunjukkan data yang paling akhir masuk.

> Kesimpulan

Front dan Rear membantu mengetahui posisi awal dan akhir antrian.

##Tugas 4 - Menu Queue Interaktif
"""

queue = []

while True:
    print("\n=== MENU QUEUE ===")
    print("1. Enqueue")
    print("2. Dequeue")
    print("3. Lihat Queue")
    print("4. Keluar")

    pilih = input("Pilih menu: ")

    if pilih == "1":
        data = input("Masukkan data: ")
        queue.append(data)

    elif pilih == "2":
        if queue:
            print("Dilayani:", queue.pop(0))
        else:
            print("Queue kosong")

    elif pilih == "3":
        print("Isi Queue:", queue)

    elif pilih == "4":
        break

"""> Langkah Kerja

1. Membuat menu menggunakan perulangan.
2. Menambahkan fitur Enqueue dan Dequeue.
3. Menampilkan isi Queue.
4. Keluar dari program saat memilih menu 4.

> Analisis

Program memungkinkan pengguna mengelola antrian secara dinamis.

> Kesimpulan

Program memungkinkan pengguna mengelola antrian secara dinamis.

##Tugas 5 - Simulasi Antrian Kasir Minimarket
"""

queue = []

queue.append("Pelanggan 1")
queue.append("Pelanggan 2")
queue.append("Pelanggan 3")

print("Antrian:", queue)

print("Dilayani:", queue.pop(0))

print("Sisa Antrian:", queue)

"""> Langkah Kerja

1. Membuat Queue pelanggan.
2. Menambahkan pelanggan ke antrian.
3. Melayani pelanggan pertama.
4. Menampilkan sisa antrian.

> Analisis

Pelanggan yang datang lebih dahulu akan dilayani terlebih dahulu sesuai konsep FIFO.

> Kesimpulan

Queue sangat cocok digunakan untuk sistem antrian kasir.

##Tugas 6 - Implementasi Queue menggunakan Deque
"""

from collections import deque

queue = deque()

queue.append("Kit")
queue.append("Branch")
queue.append("Lili")

print(queue)

queue.popleft()

print(queue)

"""> Langkah Kerja

1. Mengimpor modul deque.
2. Membuat Queue menggunakan deque.
3. Menambahkan data dengan append().
4. Menghapus data depan dengan popleft().

> Analisis

Deque lebih efisien dibanding list karena penghapusan data depan tidak memerlukan pergeseran elemen.

> Kesimpulan

Deque merupakan implementasi Queue yang lebih cepat dan efisien.

##Tugas 7 - Perbandingan Queue List dan Deque
"""

from collections import deque

# List
queue_list = ["A", "B", "C"]
queue_list.pop(0)

# Deque
queue_deque = deque(["A", "B", "C"])
queue_deque.popleft()

"""> Langkah Kerja

1. Membuat Queue menggunakan List.
2. Membuat Queue menggunakan Deque.
3. Melakukan operasi penghapusan data depan.
4. Membandingkan kinerjanya.

> Analisis

| Operasi         | List         | Deque       |
| --------------- | ------------ | ----------- |
| Tambah Belakang | O(1)         | O(1)        |
| Hapus Depan     | O(n)         | O(1)        |
| Efisiensi       | Lebih Lambat | Lebih Cepat |

> Kesimpulan

Deque lebih direkomendasikan untuk implementasi Queue karena lebih efisien.

##Tugas 8 - Simulasi Sistem Antrian Rumah Sakit
"""

from collections import deque

antrian = deque()

antrian.append("Pasien A")
antrian.append("Pasien B")
antrian.append("Pasien C")

print("Antrian:", antrian)

print("Dipanggil:", antrian.popleft())

print("Sisa Antrian:", antrian)

"""> Langkah Kerja

1. Membuat antrian pasien.
2. Menambahkan pasien yang datang.
3. Memanggil pasien pertama.
4. Menampilkan sisa antrian.

> Analisis

Pasien yang datang lebih dahulu akan mendapatkan pelayanan lebih dahulu.

> Kesimpulan

Queue sesuai digunakan untuk sistem pelayanan rumah sakit.

##Tugas 9 - Simulasi Printer Queue
"""

from collections import deque

printer = deque()

printer.append("Laporan.pdf")
printer.append("Tugas.docx")
printer.append("Foto.jpg")

while printer:
    print("Mencetak:", printer.popleft())

"""> Langkah Kerja

1. Membuat antrian dokumen.
2. Menambahkan dokumen ke Queue.
3. Mencetak dokumen sesuai urutan masuk.

> Analisis

Dokumen dicetak berdasarkan urutan pengiriman sehingga tidak terjadi konflik proses.

> Kesimpulan

Printer Queue merupakan penerapan nyata struktur data Queue.

##Tugas 10 - Simulasi Call Center Koperasi
"""

from collections import deque

call_center = deque()

call_center.append("Pelanggan 1")
call_center.append("Pelanggan 2")
call_center.append("Pelanggan 3")

while call_center:
    print("Melayani:", call_center.popleft())

"""> Langkah Kerja

1. Membuat antrian pelanggan.
2. Menambahkan pelanggan yang menelepon.
3. Melayani pelanggan sesuai urutan.

> Analisis

Pelanggan yang menghubungi lebih dahulu akan mendapatkan pelayanan lebih dahulu.

> Kesimpulan

Queue membantu menciptakan pelayanan yang adil dan teratur pada sistem call center.

##Tugas 11 - Implementasi Deque untuk Playlist Musik
"""

from collections import deque

playlist = deque()

playlist.append("Mrs. Magic Song")
playlist.append("Golden Brown Song")
playlist.appendleft("Luminary Song")

print("Playlist:", playlist)

playlist.pop()
print("Setelah pop:", playlist)

playlist.popleft()
print("Setelah popleft:", playlist)

"""> Langkah Kerja

1. Membuat playlist menggunakan deque.
2. Menambah lagu dari depan dan belakang.
3. Menghapus lagu dari depan dan belakang.
4. Menampilkan hasil.

> Analisis

Deque memberikan fleksibilitas untuk mengelola playlist dari kedua sisi.

> Kesimpulan

Deque lebih fleksibel dibanding Queue biasa karena dapat melakukan operasi pada kedua ujung.

##Tugas 12 - Analisis Kompleksitas

| Operasi             | Kompleksitas |
| ------------------- | ------------ |
| Enqueue (`append`)  | O(1)         |
| Dequeue (`popleft`) | O(1)         |
| Front               | O(1)         |
| Rear                | O(1)         |
| Appendleft          | O(1)         |
| Pop                 | O(1)         |
| Popleft             | O(1)         |

> Analisis

- Sistem Rumah Sakit menggunakan append() dan popleft() → O(1)
- Printer Queue menggunakan append() dan popleft() → O(1)
- Call Center menggunakan append() dan popleft() → O(1)
- Playlist Musik menggunakan append(), appendleft(), pop(), dan popleft() → O(1)

> Kesimpulan

Implementasi Queue dan Deque menggunakan collections.deque sangat efisien karena hampir seluruh operasinya memiliki kompleksitas O(1) sehingga cocok digunakan untuk pengolahan data secara real-time dan skala besar.
"""